import { Layout, Link } from "nextra-theme-docs";
import { Banner, Head } from "nextra/components";
import { getPageMap } from "nextra/page-map";
import "nextra-theme-docs/style.css";
import "./globals.css";
import ThemeSwitch from "@/components/ThemeSwitch";
import React from "react";

export const metadata = {
  title: "IRC",
};

const banner = (
  <Banner storageKey="some-key">
    City University of science and information technology
  </Banner>
);
const navbar = (
  <nav className="w-ful h-[60px] px-1 flex items-center py-3 justify-between">
    <img src="/logo.svg" alt="irc-logo" className="h-full" />
    <div className="flex gap-1 items-center gap-2">
      {["docs", "examples"].map((item, index) => (
        <Link key={index} href={item} className=" capitalize">
          {item}
        </Link>
      ))}
      <ThemeSwitch />
    </div>
  </nav>
);
const footer = <footer>Footer goes here</footer>;

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      // Not required, but good for SEO
      lang="en"
      // Required to be set
      dir="ltr"
      // Suggested by `next-themes` package https://github.com/pacocoursey/next-themes#with-app
      suppressHydrationWarning
    >
      <Head
      // ... Your additional head options
      >
        {/* Your additional tags should be passed as `children` of `<Head>` element */}
      </Head>
      <body>
        <Layout
          banner={banner}
          navbar={navbar}
          pageMap={await getPageMap()}
          docsRepositoryBase="https://github.com/shuding/nextra/tree/main/docs"
          footer={footer}
          // ... Your additional layout options
        >
          {children}
        </Layout>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import ThemeSwitch from "@/components/ThemeSwitch";
// import Link from "next/link";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <nav className="w-ful h-[60px] px-1 flex items-center py-3 justify-between">
//           <img src="/logo.svg" alt="irc-logo" className="h-full" />
//           <div className="flex gap-1 items-center gap-2">
//             {["docs", "examples"].map((item, index) => (
//               <Link key={index} href={item} className=" capitalize">
//                 {item}
//               </Link>
//             ))}
//             <ThemeSwitch />
//           </div>
//         </nav>
//         {children}
//         <footer className=" h-[50vh]">
//           <h1 className="normal-heading">Footer goes here</h1>
//         </footer>
//       </body>
//     </html>
//   );
// }
